api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

app_name = 'api'

urlpatterns = [
    url(r'questions/$', views.QuestionList.as_view(), name='questions'),
    url(r'questions/(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(),
        name='question'),
    url(r'all_courses/$', views.AllCourseList.as_view(), name='all_courses'),
    url(r'get_courses/$', views.CourseList.as_view(), name='get_courses'),
    url(r'start_quiz/(?P<course_id>[0-9]+)/(?P<quiz_id>[0-9]+)/$', views.StartQuiz.as_view(),
        name='start_quiz'),
    url(r'quizzes/$', views.QuizList.as_view(), name='quizzes'),
    url(r'quizzes/(?P<pk>[0-9]+)/$', views.QuizDetail.as_view(), name='quiz'),
    url(r'questionpapers/$', views.QuestionPaperList.as_view(),
        name='questionpapers'),
    url(r'questionpapers/(?P<pk>[0-9]+)/$',
        views.QuestionPaperDetail.as_view(), name='questionpaper'),
    url(r'answerpapers/$', views.AnswerPaperList.as_view(),
        name='answerpapers'),
    url(r'validate/(?P<answerpaper_id>[0-9]+)/(?P<question_id>[0-9]+)/$',
        views.AnswerValidator.as_view(), name='validators'),
    url(r'validate/(?P<uid>[0-9]+)/$',
        views.AnswerValidator.as_view(), name='validator'),
    url(r'course/(?P<pk>[0-9]+)/$',
        views.GetCourse.as_view(), name='get_course'),
    url(r'quit/(?P<answerpaper_id>\d+)/$', views.QuitQuiz.as_view(),
        name="quit_quiz"),
    url(r'login/$', views.login, name='login'),
    url(r'get_subjects/$', views.AllModuleList.as_view(), name='get_subjects'),
    url(r'get_subject/$', views.PartiModule.as_view(), name='get_subject'),
    url(r'current_affairs/$', views.CurrentAffairView.as_view(), name='current_affair'),
    url(r'updates/$', views.UpdateView.as_view(), name='update_api'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

letsprepare/urls.py
from django.conf.urls import url
from letsprepare import views
from yaksh.views import select_exam, initiate_dashboard
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^show_modules/$', views.show_all_modules, name="home"),
    url(r'^exam/$', views.show_all_quizzes, name='quizzes'),
    url(r'^results/$', views.show_results, name='results'),
    url(r'^buy/$', views.show_all_on_sale, name='buy'),
    url(r'^assign_quizzes/$', views.assign_quizzes, name='assign_quizzes'),
    url(r'^report_error/$', views.report_error, name='report_error'),
    url(r'^send_otp/$', views.send_otp, name='report_error'),
    url(r'^verify_payment/$', views.verify_payment, name='get_payment'),
    url(r'^test-series/$', TemplateView.as_view(template_name='portal_pages/test-series.html')),
    url(r'^tests/$', TemplateView.as_view(template_name='portal_pages/tests.html')),
    url(r'^select-exams/$', select_exam, name='select-exam'),
    url(r'^prev-tests/$', TemplateView.as_view(template_name='portal_pages/prev-tests.html')),
    url(r'^detailed-news/$', TemplateView.as_view(template_name='portal_pages/detailed-news.html')),
    url(r'^current-affairs/$', views.current_affairs_all, name='all_current_affairs'),
    url(r'^current-affairs/(?P<month>\d+)/(?P<year>\d+)/$', views.current_affairs_month, name='current_affairs_month'),
    url(r'^home/$', initiate_dashboard, name="Home"),
    url(r'^buy2/$', TemplateView.as_view(template_name='buy/all_on_sale.html')),
    url(r'^result_updates/$', views.result, name='update_result'),
    url(r'^announcements_updates/$', views.announcements, name='update_announcement'),
    url(r'^admit_card_updates/$', views.admit_card, name='update_admit_card'),
    url(r'^detailed-news/(?P<ca_id>\d+)/$',
        views.detailed_news,
        name='current_affair-detail'),
]

online_test/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from online_test import views
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'online_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^robots.txt/', include('robots.urls')),
    url(r'^account/', include('allauth.urls')),
    url(r'^reset_password/', views.reset_password, name='reset_password'),
    url(r'^terms/', views.return_terms, name='terms'),
    url(r'^$', views.index, name='index'),
    url(r'^exam/', include(('yaksh.urls', 'yaksh'))),
    url(r'^exam/reset/', include('django.contrib.auth.urls')),
    url(r'^', include('social_django.urls', namespace='social')),
    url(r'^grades/', include(('grades.urls', 'grades'))),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^letsprepare/', include(('letsprepare.urls', 'letsprepare'), namespace='letsprepare')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yaksh/urls.py
from django.conf.urls import url
from django.urls import path
from yaksh import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^update_email/$', views.update_email, name="update_email"),
    url(r'^activate/(?P<key>.+)$', views.activate_user, name="activate"),
    url(r'^new_activation/$', views.new_activation, name='new_activation'),
    url(r'^toggle_moderator/$', views.toggle_moderator_role,
        name='toggle_moderator'),
    url(r'^select_exam/$', views.select_exam, name='select_exam'),
    url(r'^dashboard/$', views.initiate_dashboard, name='initiate_dashboard'),
    url(r'^dashboard/(?P<course_id>\d+)/$', views.dashboard, name='dashboard'),
    url(r'^subjects/$', views.initiate_subjects, name='initiate_subject'),
    url(r'^subjects/(?P<course_id>\d+)/$', views.subjects, name='subjects'),
    url(r'^test-series/$', views.test_series, name='test_series'),
    url(r'^add_test_to_series/$', views.add_test_to_series, name='add_test_to_series'),
    url(r'^delete-test/(?P<test_id>\d+)/$', views.delete_test, name='delete_quiz_in_series'),
    url(r'^delete-series/(?P<series_id>\d+)/$', views.delete_series, name='delete_series'),
    url(r'^quizzes/$', views.quizlist_user, name='quizlist_user'),
    url(r'^results/$', views.results_user),
    # url(r'^start/(?P<questionpaper_id>\d+)/$', views.lp_start, name="start_quiz"),
    url(r'^start/(?P<questionpaper_id>\d+)/(?P<module_id>\d+)/'
        '(?P<course_id>\d+)/$', views.start, name="start_quiz"),
    url(r'^start/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$', views.start,
        name="start_quiz"),
    url(r'^quit/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$', views.quit,
        name="quit_quiz"),
    url(r'^complete/$', views.complete, name="complete"),
    url(r'^complete/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$', views.complete,
        name="complete"),
    url(r'^register/$', views.user_register, name="register"),
    url(r'^(?P<q_id>\d+)/check/$', views.check, name="check"),
    url(r'^get_result/(?P<uid>\d+)/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_result),
    url(r'^(?P<q_id>\d+)/check/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.check, name="check"),
    url(r'^(?P<q_id>\d+)/skip/(?P<attempt_num>\d+)/(?P<module_id>\d+)/'
        '(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip, name="skip_question"),
    url(r'^(?P<q_id>\d+)/skip/(?P<next_q>\d+)/(?P<attempt_num>\d+)/'
        '(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip, name="skip_question"),
    url(r'^enroll_request/(?P<course_id>\d+)/$', views.enroll_request,
        name='enroll_request'),
    url(r'^enroll_in_course/(?P<course_id>\d+)/$', views.enroll_request_dash,
        name='enroll_dash'),
    url(r'^self_enroll/(?P<course_id>\d+)/$', views.self_enroll,
        name='self_enroll'),
    url(r'^anon_enroll/(?P<course_id>\d+)/$', views.anon_enroll,
        name='anon_enroll'),
    url(r'^view_answerpaper/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)$',
        views.view_answerpaper, name='view_answerpaper'),
    url(r'^download/user_assignment/(?P<question_id>\d+)/(?P<user_id>\d+)/'
        '(?P<quiz_id>\d+)/(?P<course_id>\d+)$',
        views.download_assignment_file, name="download_user_assignment"),
    url(r'^show_lesson/(?P<lesson_id>\d+)/(?P<module_id>\d+)/'
        '(?P<course_id>\d+)/$', views.show_lesson, name='show_lesson'),
    url(r'^quizzes/view_module/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.view_module, name='view_module'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/'
        '(?P<current_unit_id>\d+)/$', views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/'
        '(?P<current_unit_id>\d+)/(?P<first_unit>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^course_modules/(?P<course_id>\d+)/$',
        views.course_modules, name='course_modules'),
    url(r'^forum/(?P<course_id>\d+)/$',
        views.course_forum,
        name='course_forum'),
    url(r'^forum/(?P<course_id>\d+)/post/(?P<uuid>[0-9a-f-]+)/$',
        views.post_comments,
        name='post_comments'),
    url(r'^forum/(?P<course_id>\d+)/post/(?P<uuid>[0-9a-f-]+)/delete/',
        views.hide_post,
        name='hide_post'),
    url(r'^forum/(?P<course_id>\d+)/comment/(?P<uuid>[0-9a-f-]+)/delete/',
        views.hide_comment,
        name='hide_comment'),
    url(r'^manage/$', views.prof_manage, name='manage'),
    url(r'^manage/addquestion/$', views.add_question, name="add_question"),
    url(r'^manage/addquestion/(?P<question_id>\d+)/$', views.add_question,
        name="add_question"),
    url(r'^manage/add_exercise/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.add_exercise, name='add_exercise'),
    url(r'^manage/add_exercise/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<quiz_id>\d+)$',
        views.add_exercise, name='edit_exercise'),
    url(r'^manage/addquiz/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.add_quiz, name='add_quiz'),
    url(r'^manage/addquiz/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<quiz_id>\d+)$',
        views.add_quiz, name='edit_quiz'),
    url(r'^manage/gradeuser/$', views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/'
        '(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.grade_user, name="grade_user"),
    url(r'^manage/questions/$', views.show_all_questions,
        name="show_questions"),
    url(r'^manage/monitor/$', views.monitor, name="monitor"),
    url(r'^manage/monitor/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.monitor, name="monitor"),
    url(r'^manage/user_data/(?P<user_id>\d+)/(?P<questionpaper_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.user_data, name="user_data"),
    url(r'^manage/user_data/(?P<user_id>\d+)/$', views.user_data),
    url(r'^manage/designquestionpaper/(?P<course_id>\d+)/(?P<quiz_id>\d+)/'
        '(?P<questionpaper_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/designquestionpaper/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/'
        '(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/'
        '(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/download_quiz_csv/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.download_quiz_csv, name="download_quiz_csv"),
    url(r'^manage/duplicate_course/(?P<course_id>\d+)/$',
        views.duplicate_course, name='duplicate_course'),
    url(r'manage/courses/$', views.courses, name='courses'),
    url(r'manage/add_course/$', views.add_course, name='add_course'),
    url(r'manage/edit_course/(?P<course_id>\d+)$', views.add_course,
        name='edit_course'),
    url(r'manage/course_detail/(?P<course_id>\d+)/$', views.course_detail,
        name='course_detail'),

    url(r'manage/enroll/(?P<course_id>\d+)/$', views.enroll_reject_user,
        name="enroll_reject_user"),
    url(r'manage/enroll/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll_user, name="enroll_user"),
    url(r'manage/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject_user, name="reject_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject_user, {'was_enrolled': True},
        name="reject_enrolled_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/$',
        views.enroll_reject_user, {'was_enrolled': True},
        name="reject_enrolled_users"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll_user, {'was_rejected': True},
        name="enroll_rejected_user"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/$',
        views.enroll_reject_user, {'was_rejected': True},
        name="enroll_rejected_users"),

    url(r'manage/upload_users/(?P<course_id>\d+)/$', views.upload_users,
        name="upload_users"),
    url(r'manage/send_mail/(?P<course_id>\d+)/$', views.send_mail,
        name="send_mail"),

    url(r'manage/toggle_status/(?P<course_id>\d+)/$',
        views.toggle_course_status, name="toggle_course_status"),
    url(r'^questions/filter$', views.questions_filter,
        name="questions_filter"),
    url(r'^editprofile/$', views.edit_profile, name='edit_profile'),
    url(r'^viewprofile/$', views.view_profile, name='view_profile'),

    url(r'^manage/searchteacher/(?P<course_id>\d+)/$', views.search_teacher,
        name="search_teacher"),
    url(r'^manage/addteacher/(?P<course_id>\d+)/$', views.add_teacher,
        name='add_teacher'),
    url(r'^manage/remove_teachers/(?P<course_id>\d+)/$', views.remove_teachers,
        name='remove_teacher'),
    url(r'^manage/download_questions/$', views.show_all_questions,
        name="download_questions"),
    url(r'^manage/upload_questions/$', views.show_all_questions,
        name="upload_questions"),
    url(r'^manage/create_modules/$', views.create_modules,
        name="create_modules"),

yaksh/templates/upgradev001/complete.html
{% extends "base4.html" %}
{% load static %}

{% block title %} Complete {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'upgradev001/css/complete.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<br>
{% if module_id and not paper.course.is_trial %}
<center>
    <div class="alert alert-info col-md-8 bg-info text-white border-bottom border-white">
        <div class="row">
            <div class="col-sm-2 col-3 text-right pl-0 pl-sm-2">
                <i class="fa fa-info-circle" style="font-size: 61px;"></i>
            </div>
            <div class="col-sm-10 col-9 text-left pl-0">
                <h3 class="mb-0">Note:</h3>
                <p>Please Click on the Next button to submit the quiz. Please do not close the browser without clicking Next.</p>
            </div>
        </div>
        <!-- <h1 class="text-left"><i class="fa fa-info-circle"></i> Info</h1>
        Note:- Please Click on the Next button to submit the quiz. Please do not close the browser without clicking Next. -->
    </div>
</center>
{% endif %}
{% csrf_token %}
    {% if paper.questions_answered.all or paper.questions_unanswered.all %}
        <center>
        <div class="col-md-8">
            <h3>Submission Status</h3>
            <table class="table table-bordered table-responsive-sm" >
                <thead>
                    <tr class="text-center sub-status">
                        <th> Question</th>
                        <th> Status </th>
                        <th></th>
                    </tr>
                </thead>

                {% for question in paper.questions.all %}
                    <tbody class="bg-light">
                        {% if question in paper.questions_answered.all %}
                            <tr class="">
                            <td> {{ question.summary }} </td>
                            <td> Attempted </td>
                            <td class="text-center"><i class="fa fa-check-circle text-success" style="font-size: 40px; font-weight: 900;"></i></td>
                        {% else %}
                            <tr class="" style="background-color: gainsboro;">
                            <td> {{ question }} </td>
                            <td>Not completed
                            </td>
                            <td class="text-center"><i class="fa fa-check-circle-o" style="font-size: 30px; color: #c58f8f;"></i></td>
                        {% endif %}
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
        </center>
    {% endif %}
    <br><br>
	<center class="container">
        <h5>
            <span class="alert alert-success">{{message}}</span>
        </h5>
    </center>
    <center class="mb-4">
        </br>
    <a href="{% url 'letsprepare:home' %}" id="home" class="btn btn-primary btn-lg"> Home </a>
    </center>
{% endblock content %}

yaksh/templates/upgradev001/exam.html
{% extends "base4.html" %}
{% load custom_filters %}
{% load static %}

{% block title %}{{ paper.question_paper.quiz.description }}{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-4">
    <span class="time-div nav-item" id="time_left"></span>
  </div>
  <div class="col-md-7">
    <form id="logout" action="{% url 'yaksh:quit_quiz' paper.attempt_number module.id paper.question_paper.id course.id %}" method="post" class="ml-auto">
      {% csrf_token %}
      <span class="nav-item"><button class="btn btn-success btn-lg" type="submit" name="quit">
        {% if paper.questions_unanswered.all %}
          Submit {{quiz_type}}
        {% else %}
          Submit {{quiz_type}}
        {% endif %}
      <i class="fa fa-check"></i></button></span>
    </form>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <!-- Main Component -->
    <div class="col-md-9">
      <br>
      {% block main %}
      {% endblock %}
    </div>
    <!-- Side Component -->
    <div class="col-md-3" style="overflow-x: scroll;">
      <div class="card" style="border-radius: 0px; border: 1px solid #28a745;">
        <div class="card-header" style="background: #b0eebf;">
      <br>
      <center>
        <b>{{course.name}}</b><br>
        {{ paper.question_paper.quiz.description }}
      </center></div>
      <div class="card-body">
      <center><p><b><u>Question Navigator</u></b></p></center>
      <br>
      <div class="justify-content-center">
        {% for qid in paper.get_all_ordered_questions %}
          {% if paper.question_paper.quiz.allow_skip %}
            {% if qid in paper.get_questions_unanswered %}
              {% if qid.id == question.id %}
              <a class="active btn btn-outline-primary " href="#"data-toggle="tooltip"
                  title="{{ qid.description|striptags|truncatechars:100 }}" style="width: 50px"
                  onclick="call_skip('{{ URL_ROOT }}/exam/{{ question.id }}/skip/{{ qid.id }}/{{ paper.attempt_number }}/{{ module.id }}/{{ paper.question_paper.id }}/{{course.id}}/')">{{ forloop.counter }}</a>
              {% else %}
              <a class=" btn btn-outline-primary " href="#" data-toggle="tooltip" title="{{ qid.description|striptags|truncatechars:100 }}" style="width: 50px"
                  onclick="call_skip('{{ URL_ROOT }}/exam/{{ question.id }}/skip/{{ qid.id }}/{{ paper.attempt_number }}/{{ module.id }}/{{ paper.question_paper.id }}/{{course.id}}/')">{{ forloop.counter }}</a>
              {% endif %}
            {% endif %}
            {% if qid in paper.get_questions_answered %}
            <a class="btn btn-success" href="#" data-toggle="tooltip" style="width: 50px"
            onclick="call_skip('{{ URL_ROOT }}/exam/{{ question.id }}/skip/{{ qid.id }}/{{ paper.attempt_number }}/{{ module.id }}/{{ paper.question_paper.id }}/{{course.id}}/')"
            title="{{ qid.description|striptags|truncatechars:100 }}">{{ forloop.counter }}</a>
            {% endif %}
          {% else %}
            {% if qid.id == question.id %}
            <a class="active btn btn-outline-primary" data-toggle="tooltip" title="{{ qid.description|striptags|truncatechars:100 }}" style="width: 50px">{{ forloop.counter }}</a>
            {% elif qid in paper.get_questions_answered %}
            <a class="btn btn-success" href="#" data-toggle="tooltip" style="width: 50px"
            onclick="call_skip('{{ URL_ROOT }}/exam/{{ question.id }}/skip/{{ qid.id }}/{{ paper.attempt_number }}/{{ module.id }}/{{ paper.question_paper.id }}/{{course.id}}/')"
            title="{{ qid.description|striptags|truncatechars:100 }}">{{ forloop.counter }}</a>
            {% else %}
            <a class="btn btn-outline-primary" style="width: 50px" data-toggle="tooltip" title="{{ qid.description|striptags|truncatechars:100 }}">{{ forloop.counter }}</a>
            {% endif %}
          {% endif %}
        {% endfor %}
      </div>
      <br>
      <p><span class="btn btn-success"></span> Attempted question(s)</p>
      <p><span class="btn btn-primary"></span> Current question</p>
      <p><span class="btn btn-outline-primary"></span> Unattempted question(s)</p>
      <br>
      <div>
        <p class="text-center">Question(s) left: <b>{{ paper.questions_left }}</b></p>
      </div>
      <br>
      <div>
          <table class="table table-bordered table-responsive-sm">
            <thead>
              <tr>
                <th>Category</th>
                <th>Question No.</th>
              </tr>
            </thead>
            <tbody>
              {% for category, question_number in paper.get_categorized_question_indices.items %}
              <tr>
                <td>
                  {{category}}
                </td>
                <td>
                  {{question_number| join:", "}}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        <br>
      </div>
      </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

yaksh/templates/upgradev001/latest_update.html
{% extends "portal_pages/base2.html" %}
{% load static %}
{% block title %}
Latest Updates
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href=" {% static 'upgradev001/css/latest_updates.css' %}" />
{% endblock %}

{% block content %}
<section class="latest-updates">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="card updates-nav">
                    <h5>Latest Updates</h5>
                    <a href="{% url 'letsprepare:update_result' %}">Result</a>
                    <a href="{% url 'letsprepare:update_admit_card' %}">Admit Card</a>
                    <a href="{% url 'letsprepare:update_announcement' %}">Announcements</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card update-nav-link">
                    {% load tz %}
                    {% localtime off %}
                    <h4>{{ heading }}</h4>
                    {% for update in page_obj %}
                    <a href="{{ update.link }}" class="updates-link">{{ update.description }}<span class="date"> {{ update.pubDate }}</span></a>
                    {% endfor %}
                    {% endlocaltime %}
                    
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a class="btn btn-outline-success mb-4" href="?page=1">&laquo; first</a>
                                <a class="btn btn-outline-success mb-4" href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% else %}
                                <a class="btn btn-outline-dark disabled mb-4" disabled>&laquo; first</a>
                                <a class="btn btn-outline-dark disabled mb-4" disabled>previous</a>
                            {% endif %}
                            {% if page_obj.number|add:'-2' > 1 %}
                                <a class="btn btn-outline-success mb-4" href="?page=1">1</a>
                                <a class="d-inline">...</a>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <a class="active mb-4" href="?page={{num}}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <a class="btn btn-outline-success mb-4" href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                            {% endfor %} 
                            {% if page_obj.number|add:'2' < page_obj.paginator.num_pages %}
                                <a class="d-inline">...</a>
                                <a class="btn btn-outline-success mb-4" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                            {% endif %}
                            {% if page_obj.has_next %}
                                
                                <a class="btn btn-outline-success mb-4" href="?page={{ page_obj.next_page_number }}">next</a>
                                <a class="btn btn-outline-success mb-4" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% else %}
                                <a class="btn btn-outline-dark disabled mb-4" disabled>&laquo; next</a>
                                <a class="btn btn-outline-dark disabled mb-4" disabled>last</a>
                            {% endif %}
                        </span>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}